<a href="https://colab.research.google.com/github/TomaszWlo/learning-git-task/blob/master/zadanie_8_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

1. Ponizej zrobione zostaly punkty z zadania od 1 - 3

In [ ]:
import pandas as pd

album = pd.read_html('https://www.officialcharts.com/chart-news/the-best-selling-albums-of-all-time-on-the-official-uk-chart__15551/', header=0)
df = album[0]

df.rename(columns={'TITLE':'TYTUŁ', "ARTIST":'ARTYSTA', 'YEAR':'ROK', 'HIGH POSN':'MAX POZ'}, inplace=True)
print(df.columns)

df['ARTYSTA'].unique()
df['ARTYSTA'].nunique()
df['ARTYSTA'].value_counts()

Index(['POS', 'TYTUŁ', 'ARTYSTA', 'ROK', 'MAX POZ'], dtype='object')

ARTYSTA
TAKE THAT                   3
COLDPLAY                    3
QUEEN                       2
ADELE                       2
MICHAEL JACKSON             2
ABBA                        2
BEATLES                     2
DIDO                        2
ORIGINAL SOUNDTRACK         2
FLEETWOOD MAC               2
ROBBIE WILLIAMS             2
PINK FLOYD                  1
DIRE STRAITS                1
MADONNA                     1
OASIS                       1
JAMES BLUNT                 1
BOB MARLEY & THE WAILERS    1
SHANIA TWAIN                1
SIMPLY RED                  1
AMY WINEHOUSE               1
SIMON & GARFUNKEL           1
MEAT LOAF                   1
LEONA LEWIS                 1
DAVID GRAY                  1
MICHAEL BUBLE               1
SPICE GIRLS                 1
CORRS                       1
LADY GAGA                   1
KINGS OF LEON               1
KEANE                       1
VERVE                       1
U2                          1
JEFF WAYNE                  1
PHIL COLLINS                1
SCISSOR SISTERS             1
ALANIS MORISSETTE           1
MIKE OLDFIELD               1
TRAVIS                      1
TRACY CHAPMAN               1
ED SHEERAN                  1
NORAH JONES                 1
PAUL SIMON                  1
ORIGINAL CAST RECORDING     1
GEORGE MICHAEL              1
EMINEM                      1
SNOW PATROL                 1
REM                         1
Name: count, dtype: int64

2. Poniżej zrobilem punkty od 4 - 6

In [ ]:
import pandas as pd

album = pd.read_html('https://www.officialcharts.com/chart-news/the-best-selling-albums-of-all-time-on-the-official-uk-chart__15551/', header=0)
df = album[0]

df.rename(columns={'TITLE':'TYTUŁ', "ARTIST":'ARTYSTA', 'YEAR':'ROK', 'HIGH POSN':'MAX POZ'}, inplace=True)
print(df.columns)

df.columns = df.columns.str.capitalize()
print(df.columns)

df.drop('Max poz', axis=1, inplace=True)
print(df.columns)


df['Rok'].value_counts()

Index(['POS', 'TYTUŁ', 'ARTYSTA', 'ROK', 'MAX POZ'], dtype='object')
Index(['Pos', 'Tytuł', 'Artysta', 'Rok', 'Max poz'], dtype='object')
Index(['Pos', 'Tytuł', 'Artysta', 'Rok'], dtype='object')

Rok
1987    4
2000    4
2006    3
1977    3
1998    3
1997    3
2004    3
1991    2
1995    2
1992    2
2005    2
2008    2
1973    2
2002    2
2011    1
1981    1
1967    1
1984    1
1990    1
1982    1
1985    1
2009    1
2007    1
1970    1
1996    1
2015    1
2003    1
1978    1
1989    1
1999    1
1988    1
1975    1
2014    1
1986    1
1965    1
2001    1
2010    1
Name: count, dtype: int64

3. Poniżej zrobilem punkt 7

---

In [ ]:
import pandas as pd

album = pd.read_html('https://www.officialcharts.com/chart-news/the-best-selling-albums-of-all-time-on-the-official-uk-chart__15551/', header=0)
df = album[0]

df.rename(columns={'TITLE':'TYTUŁ', "ARTIST":'ARTYSTA', 'YEAR':'ROK', 'HIGH POSN':'MAX POZ'}, inplace=True)
print(df.columns)

df.columns = df.columns.str.capitalize()
print(df.columns)

df.drop('Max poz', axis=1, inplace=True)
print(df.columns)

len(df[(df['Rok']>1960) | (df['Rok'] < 1990)])

Index(['POS', 'TYTUŁ', 'ARTYSTA', 'ROK', 'MAX POZ'], dtype='object')
Index(['Pos', 'Tytuł', 'Artysta', 'Rok', 'Max poz'], dtype='object')
Index(['Pos', 'Tytuł', 'Artysta', 'Rok'], dtype='object')

60

4. Poniżej zrobilem punkt od 8 - 10

---

In [ ]:
import pandas as pd

album = pd.read_html('https://www.officialcharts.com/chart-news/the-best-selling-albums-of-all-time-on-the-official-uk-chart__15551/', header=0)
df = album[0]

df.rename(columns={'TITLE':'TYTUŁ', "ARTIST":'ARTYSTA', 'YEAR':'ROK', 'HIGH POSN':'MAX POZ'}, inplace=True)
print(df.columns)

df.columns = df.columns.str.capitalize()
print(df.columns)

df.drop('Max poz', axis=1, inplace=True)
print(df.columns)

print(df['Rok'].min())

df.sort_values(by='Rok').to_csv('Sorted table')

Index(['POS', 'TYTUŁ', 'ARTYSTA', 'ROK', 'MAX POZ'], dtype='object')
Index(['Pos', 'Tytuł', 'Artysta', 'Rok', 'Max poz'], dtype='object')
Index(['Pos', 'Tytuł', 'Artysta', 'Rok'], dtype='object')
1965

,Pos,Tytuł,Artysta,Rok
51,52,THE SOUND OF MUSIC,ORIGINAL CAST RECORDING,1965
2,3,SGT PEPPER'S LONELY HEARTS CLUB BAND,BEATLES,1967
20,21,BRIDGE OVER TROUBLED WATER,SIMON & GARFUNKEL,1970
6,7,THE DARK SIDE OF THE MOON,PINK FLOYD,1973
41,42,TUBULAR BELLS,MIKE OLDFIELD,1973
45,46,GREATEST HITS,ABBA,1975
18,19,BAT OUT OF HELL,MEAT LOAF,1977
10,11,RUMOURS,FLEETWOOD MAC,1977
46,47,GREASE,ORIGINAL SOUNDTRACK,1977
36,37,THE WAR OF THE WORLDS,JEFF WAYNE,1978
0,1,GREATEST HITS,QUEEN,1981
5,6,THRILLER,MICHAEL JACKSON,1982
15,16,LEGEND,BOB MARLEY & THE WAILERS,1984
7,8,BROTHERS IN ARMS,DIRE STRAITS,1985
50,51,GRACELAND,PAUL SIMON,1986
21,22,DIRTY DANCING,ORIGINAL SOUNDTRACK,1987
53,54,TANGO IN THE NIGHT,FLEETWOOD MAC,1987
35,36,THE JOSHUA TREE,U2,1987
8,9,BAD,MICHAEL JACKSON,1987
43,44,TRACY CHAPMAN,TRACY CHAPMAN,1988
38,39,BUT SERIOUSLY,PHIL COLLINS,1989
11,12,THE IMMACULATE COLLECTION,MADONNA,1990
13,14,STARS,SIMPLY RED,1991
9,10,GREATEST HITS II,QUEEN,1991
1,2,GOLD - GREATEST HITS,ABBA,1992
59,60,AUTOMATIC FOR THE PEOPLE,REM,1992
40,41,JAGGED LITTLE PILL,ALANIS MORISSETTE,1995
4,5,WHAT'S THE STORY MORNING GLORY,OASIS,1995
28,29,SPICE,SPICE GIRLS,1996
27,28,TALK ON CORNERS,CORRS,1997
14,15,COME ON OVER,SHANIA TWAIN,1997
17,18,URBAN HYMNS,VERVE,1997
47,48,I'VE BEEN EXPECTING YOU,ROBBIE WILLIAMS,1998
52,53,LADIES & GENTLEMEN - THE BEST OF,GEORGE MICHAEL,1998
25,26,WHITE LADDER,DAVID GRAY,1998
42,43,THE MAN WHO,TRAVIS,1999
54,55,THE MARSHALL MATHERS LP,EMINEM,2000
24,25,NO ANGEL,DIDO,2000
19,20,1,BEATLES,2000
44,45,PARACHUTES,COLDPLAY,2000
55,56,SWING WHEN YOU'RE WINNING,ROBBIE WILLIAMS,2001
30,31,A RUSH OF BLOOD TO THE HEAD,COLDPLAY,2002
49,50,COME AWAY WITH ME,NORAH JONES,2002
31,32,LIFE FOR RENT,DIDO,2003
37,38,SCISSOR SISTERS,SCISSOR SISTERS,2004
34,35,HOPES AND FEARS,KEANE,2004
16,17,BACK TO BEDLAM,JAMES BLUNT,2004
58,59,NEVER FORGET - THE ULTIMATE COLLECTION,TAKE THAT,2005
39,40,X&Y,COLDPLAY,2005
12,13,BACK TO BLACK,AMY WINEHOUSE,2006
57,58,EYES OPEN,SNOW PATROL,2006
33,34,BEAUTIFUL WORLD,TAKE THAT,2006
22,23,SPIRIT,LEONA LEWIS,2007
32,33,ONLY BY THE NIGHT,KINGS OF LEON,2008
29,30,THE FAME,LADY GAGA,2008
23,24,CRAZY LOVE,MICHAEL BUBLE,2009
56,57,PROGRESS,TAKE THAT,2010
3,4,21,ADELE,2011
48,49,X,ED SHEERAN,2014
26,27,25,ADELE,2015